version: 0.0
os: linux
files:
  - source: /
    destination: /temp
    overwrite: true

hooks:
  ApplicationStart:
    - location: scripts/auto_deploy.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root