  version: 0.0
  os: linux
  files:
    - source: /
      destination: /home/ubuntu/nextjs/exam-master/
      overwrite: true
  file_exists_behavior: OVERWRITE

  hooks:
    BeforeInstall:
      - location: scripts/before-install.sh
        timeout: 300
        runas: ubuntu
    AfterInstall:
      - location: scripts/after-install.sh
        timeout: 300
        runas: ubuntu
    ApplicationStart:
      - location: scripts/application-start.sh
        timeout: 300
        runas: ubuntu