version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/CodeDeploy
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/auto_deploy.sh
      timeout: 300
      runas: root