version: 0.0
os: linux
files:

hooks:
  ApplicationStart:
    - location: scripts/auto_deploy.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/swap_traffic.sh
      timeout: 300
      runas: root