  name: exam-master Node.js CI

  on:
    push:
      branches: ["main"]

  jobs:
    build:
      name: Build
      runs-on: self-hosted
      strategy:
        matrix:
          node-version: [20.x]
      steps:
        - uses: actions/checkout@v3

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}

        - name: Create .env file
          uses: ozaytsev86/create-env-file@v1
          with:
            ENV_DATABASE_URL: ${{ secrets.DATABASE_URL }}
            ENV_AWS_CLOUDFRONT_DOMAIN: ${{ secrets.AWS_CLOUDFRONT_DOMAIN }}
            NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
            AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
            AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
            AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
            AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
            NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
            SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
            SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
            NEXT_PUBLIC_GTM: ${{ secrets.NEXT_PUBLIC_GTM }}
            NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
            NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
            GOOGLE_API: ${{ secrets.GOOGLE_API }}
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            
        - name: "Build project"
          run: |
            npm install
            npm run build
            rm -r node_modules

        - name: AWS CodeDeploy
          uses: sourcetoad/aws-codedeploy-action@v1
          with:
            aws_access_key: ${{ secrets.AWS_SECRET_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
            aws_region: ap-northeast-2
            codedeploy_name: exam-master
            codedeploy_group: Dev
            codedeploy_register_only: false
            s3_bucket: exam-master-build
            s3_folder: dev
            max_polling_iterations: 0
            directory: ./
